/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl */

#ifndef _Included_dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl
#define _Included_dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl
 * Method:    initTextDao
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl_initTextDao
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl
 * Method:    destructTextDao
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl_destructTextDao
  (JNIEnv *, jobject);

/*
 * Class:     dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl
 * Method:    findAll
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl_findAll
  (JNIEnv *, jobject);

/*
 * Class:     dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl
 * Method:    insert
 * Signature: (Ldk/bobbyz/crosscppandroidapp/commonlibrary/model/Text;)V
 */
JNIEXPORT void JNICALL Java_dk_bobbyz_crosscppandroidapp_commonlibrary_impl_TextDaoImpl_insert
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
