/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_bobbyz_crosscppandroidapp_CommonLibrary */

#ifndef _Included_dk_bobbyz_crosscppandroidapp_CommonLibrary
#define _Included_dk_bobbyz_crosscppandroidapp_CommonLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_bobbyz_crosscppandroidapp_CommonLibrary
 * Method:    CommonLibrary
 * Signature: ()Ldk/bobbyz/crosscppandroidapp/CommonLibrary;
 */
JNIEXPORT jobject JNICALL Java_dk_bobbyz_crosscppandroidapp_CommonLibrary_CommonLibrary
  (JNIEnv *, jobject);

/*
 * Class:     dk_bobbyz_crosscppandroidapp_CommonLibrary
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_bobbyz_crosscppandroidapp_CommonLibrary_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
