

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Button;
                ref class ListView;
            }
        }
    }
}

namespace CrossCppWPApp
{
    partial ref class Rest : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtComment;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtEmail;
        private: ::Windows::UI::Xaml::Controls::Button^ btnPost;
        private: ::Windows::UI::Xaml::Controls::Button^ btnGet;
        private: ::Windows::UI::Xaml::Controls::ListView^ lvComments;
    };
}

